language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
branches:
  only:
    - /^7.x/
env:
  - FEDORA_VERSION="3.5"
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
  - FEDORA_VERSION="3.8.1"
before_install:
  - cd $HOME
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - git clone -b 7.x git://github.com/Islandora/islandora_paged_content.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solution_pack_collection.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solution_pack_large_image.git
  - git clone -b 7.x git://github.com/Islandora/islandora_ocr.git
  - export ISLANDORA_DIR=$HOME/islandora
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - sudo sh $TRAVIS_BUILD_DIR/tests/scripts/adore.sh
  - sudo sh $TRAVIS_BUILD_DIR/tests/scripts/tesseract.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/islandora_solution_pack_book
  - ln -s $HOME/islandora_paged_content sites/all/modules/islandora_paged_content
  - ln -s $HOME/islandora_solution_pack_collection sites/all/modules/islandora_solution_pack_collection
  - ln -s $HOME/islandora_ocr sites/all/modules/islandora_ocr
  - ln -s $HOME/islandora_solution_pack_large_image sites/all/modules/islandora_solution_pack_large_image
  - drush dl imagemagick
  - drush en --user=1 --yes islandora_ocr islandora_large_image imagemagick islandora_book islandora_basic_collection
  - drush vset islandora_ocr_tesseract `which tesseract`
  - drush vset islandora_book_tesseract `which tesseract`
script:
  - ant -buildfile sites/all/modules/islandora_solution_pack_book/build.xml lint
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/islandora_solution_pack_book
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora_book
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/islandora_solution_pack_book
  - drush test-run --user=1 --uri=http://localhost:8081 "Islandora Book"
notifications:
  irc: "irc.freenode.org#islandora"
